spring.datasource.url=mysql://b21f0e80e78c11:cec046c3@us-cdbr-east-02.cleardb.com/heroku_5f217ac9009d941?reconnect=true

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.format_sql=false